SECRET_KEY = b'_5#y2L"F4Q8z\n\xec]/'
SQLALCHEMY_DATABASE_URI = 'sqlite:///pdfsign.sqlite3'

DEFAULT_CERT_COUNTRY_NAME = 'COUNTRY'
DEFAULT_CERT_LOCALITY_NAME = 'LOCALITY'
DEFAULT_CERT_STATE_OR_PROVINCE_NAME = 'STATE'
DEFAULT_CERT_ORGANIZATION_NAME = 'ORG'
DEFAULT_CERT_ORGANIZATION_UNIT_NAME = 'ORG_UNIT'
DEFAULT_CERT_SERIAL_NUMBER = 0

CERTS_DIRECTORY = 'var/certs'
PRIVATE_DIRECTORY = 'var/private'
